version: '3.8'

services:
  web:
    container_name: Portfolio_Backend
    build:
      context: ..
      dockerfile: ops/Dockerfile
    env_file:
      - ../app/.env
    volumes:
      - ../:/usr/src/
    ports:
      - "8000:80"